name: Build plantuml from source

on:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Checkout plantuml
        uses: actions/checkout@v3
        with:
          repository: 'plantuml/plantuml'
          ref: 'wasm'
          path: 'plantuml_source'


      - name: Set up java
        uses: actions/setup-java@v3.5.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle


      - name: Build artifacts
        working-directory: ./plantuml_source
        run: |
          gradle -q clean build \
            pdfJar \
            generateMetadataFileForMavenPublication generatePomFileForMavenPublication \
            -x test

      - name: Copy jars
        working-directory: ./plantuml_source
        run: |
          export POM_VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}')
          rm ../source-jars/plantuml-wasm.jar
          cp build/libs/plantuml-$POM_VERSION.jar ../source-jars/plantuml-wasm.jar
          ls -ls ../source-jars/


      - name: Cleanup plantuml
        run: |
          rm -rf plantuml_source

      - name: Recompile jars
        run: |
          bash compile.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Build plantuml from source
          delete-branch: true
          title: '[Sync plantuml] Build plantuml from source'
          body: |
            Automated sync plantuml from source.
          labels: |
            automated pr
          team-reviewers: |
            owners
            maintainers
