name: Update example PUMLs list
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            examples/**/*.puml
      - name: PUML files considered echo output
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Regenerate example puml list
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          bash update_example_pumls_list.sh
      - name: Push Local Changes
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Update example pumls list"
          branch: ${{ github.head_ref }}
